apiVersion: v1
kind: Pod
metadata:
  name: nginx-initcontainers-demo-1
  labels:
    item: haha
spec:
  volumes:
  - name: data
    emptyDir: {}
  initContainers:
  - name: init-data-1
    image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
    command:
    - 'sh'
    - '-c'
    - "for i in $(seq 1 5);do echo '<h1>'$(date +%F-%T)'</h1>' >> /data/index.html;sleep 2;done"
    volumeMounts:
    - mountPath: "/data"
      name: data
  - name: init-data-2
    image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
    command:
    - 'sh'
    - '-c'
    - "chmod 644 -R /data/*"
    volumeMounts:
    - mountPath: "/data"
      name: data
  containers:
  - name: nginx-initcontainers-demo
    image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: data
