apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    item: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: {{ .Values.label.key_name }}
      values:
      - {{ .Values.label.key_value }}
      operator: In
  template:
    metadata:
      labels:
        {{ .Values.label.key_name }}: {{ .Values.label.key_value }} 
    spec:
      volumes:
      - name: nginx
        configMap:
          name: {{ .Values.volumes.cm_name }}
          items:
          - key: nginx.conf
            path: nginx.conf  
      - name: {{ .Values.label.key_value }}
        configMap:
          name: {{ .Values.volumes.cm_name }}
          items:
          - key: {{ .Values.volumes.cm_items.key }}
            path: {{ .Values.volumes.cm_items.path }}
      - name: code
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      containers:
      - name: games-nginx
        image: {{ .Values.image.repository }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: {{ .Values.label.key_value }}
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: {{ .Values.volumes.cm_items.path }}
        - name: code
          mountPath: /usr/share/nginx/html
