apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-bird-pvc
  namespace: games
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
    limits:
      storage: 2G
      
  
