apiVersion: v1
kind: Service
metadata:
  name: games-bird-svc
  namespace: games
  labels:
    item: bird
spec:
  selector:
    app: bird
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
