apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-01
  namespace: haha
  labels:
    item: haha-svc
spec:
  selector:
    app: wahaha1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
    protocol: TCP
  clusterIP: 10.200.111.111
status: {}
