apiVersion: v1
kind: Service
metadata:
  name: linux-headless
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    apps: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-web-sts-vct
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "managed-nfs-storage"
      resources:
        requests:
          storage: 2Gi
  serviceName: linux-headless
  replicas: 3
  selector:
    matchLabels: 
      apps: nginx
  template:
    metadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx-web-01
        image: harbor.myharbor.com/myharbor/nginx:v1.0-my
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-sts-svc
spec:
  selector:
    apps: nginx
  ports:
  - port: 80
    targetPort: 80
