apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-svc-demo-1
  labels:
    item: haha
spec:
  replicas: 2
  selector:
    version: v1.0
    app: haha-1
  template:
    metadata:
      labels:
        version: v1.0
        app: haha-1
    spec:
      containers:
        - name: nginx-demo-1
          image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-1
  labels:
    item: haha
spec:
  selector:
    version: v1.0
    app: haha-1
  type: ClusterIP
  ports:
    - port: 58888
      targetPort: 80
      protocol: TCP
  clusterIP: 10.200.111.101

