apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-readiness-1
  labels: 
    item: haha
  namespace: item-haha
spec:
  replicas: 3
  selector:
    version: v1.0
    app: dm
  template:
    metadata:
      labels:
        version: v1.0
        app: dm
    spec: 
      restartPolicy: Always
#      hostName: 
      hostNetwork: false
      containers:
      - name: nginx-demo-1
        image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - touch /tmp/readinesshealth; sleep 30; rm -f /tmp/readinesshealth; sleep 120
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/readinesshealth
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-readiness-svc-1
  labels:
    apps: nginx-svc-1
  namespace: item-haha
spec:
  selector:
    version: v1.0
    app: dm
  type: ClusterIP
  clusterIP: 10.200.100.101
  ports:
  - port: 8889
    targetPort: 80
    protocol: TCP
