apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo-volumes-nfs
  labels:
    app: volumes-nfs
spec:
  hostNetwork: true
  nodeName: centos7k8s2
  restartPolicy: OnFailure
  volumes:
  - name: data-01
    nfs: 
      server: 192.168.76.141
      path: /data/haha/html
  containers:
  - name: nginx-demo
    image: harbor.myharbor.com/myharbor/nginx:1.24-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data-01
      mountPath: /usr/share/nginx/html 
