---
- hosts: ww_admin_main
  tasks:
    - name: add ip into admin_ip.conf
      shell: sed -Ei "s@((([0-9]{1,3}\.?){4})+)@\1|{{ ip }}@"  /data/.wadmin/nginx/conf.d/admin_ip.ini
    - name: test nginx
      shell: docker exec -it wadmin nginx -t
    - name: reload nginx
      shell: docker exec -it wadmin nginx -s reload
- hosts: ww_admin_yfb
  tasks:
    - name: add ip into admin_ip.conf
      shell: sed -Ei "s@((([0-9]{1,3}\.?){4})+)@\1|{{ ip }}@" /data/etc/nginx/conf.d/admin_ip.ini
    - name: test nginx
      shell: docker exec -it wwp nginx -t
    - name: reload nginx
      shell: docker exec -it wwp nginx -s reload
