---
- hosts: chat_history_admin
  tasks:
    - name: add ip into admin_ip.conf
      shell: sed -Ei "s@((\|?){{ ip }}\|?)@\2@" /home/www/config/admin_ip.conf
    - name: restart admin
      shell: docker-compose -f /home/www/docker-compose.yml restart chat_admin
