---
- hosts: hongbao_admin
  tasks:
  - name: del ip from admin_ip.ini
    shell: sed -Ei "s@((\|?){{ ip }}\|?)@\2@" /www/server/nginx/conf/hongbaoadmin_ip.ini 
  - name: restart admin
    shell: nginx -s reload
