apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: yohaha-python
roleRef:
  kind: Role
  name: python-role
  apiGroup: rbac.authorization.k8s.io
  
