version: '3.1'

services:

  redis:
    image: redis7012:v1
    container_name: redis7012
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - /opt/redis/data:/data
      - /opt/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
#      - /opt/redis/logs/redis.log:/var/log/redis.log
#    network_mode: host
    command:
      redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 2048m
    networks:
       net_app:
         ipv4_address: 172.20.0.3
networks:
  net_app: 
    external: true

