apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: haha
spec:
  selector: 
    app: wordpress1
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
