apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-wordpress-demo
  labels:
    item: wordpress
  namespace: haha
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      values:
      - wordpress1
      operator: In
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 3
#      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: wordpress1
    spec:
      #hostNetwork: true
      containers:
      - name: web-wordpress-demo-1
        image: harbor.myharbor.com/myharbor/wordpress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-wordpress"
        - name: WORDPRESS_DB_USER
          value: "wordpress_user"
        - name: WORDPRESS_DB_PASSWORD
          value: "123456"   
        #resources:
        #  requests:
        #    cpu: '0.5'
        #    memory: '0.5G'
        #  limits:
        #    cpu: '1'
        #    memory: '1G'
