apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001-nfs
spec:
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.76.142
    path: /opt/data/k8s/pv/pv001
  capacity:
    storage: 2G
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002-nfs
spec:
  accessModes:   
  - ReadWriteMany
  nfs:
    server: 192.168.76.142
    path: /opt/data/k8s/pv/pv002
  capacity:
    storage: 5G
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003-nfs
spec:
  accessModes:   
  - ReadWriteMany
  nfs:
    server: 192.168.76.142
    path: /opt/data/k8s/pv/pv003
  capacity:
    storage: 8G
  persistentVolumeReclaimPolicy: Retain
