apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-nginx-demo
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: apps
      operator: Exists
  template:
    metadata:
      labels:
        apps: pvcnginx
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pv-pvc-demo
      containers:
      - name: pvc-nginx-web
        image: harbor.myharbor.com/myharbor/nginx:v1.0-my
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: pvc-nginx-svc
spec:
  selector: 
    apps: pvcnginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
