apiVersion: v1
kind: Service
metadata:
  name: web-wordpress-svc
  namespace: mywordpress
spec:
  selector:
    app: wordpress1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
  clusterIP: 10.200.100.188
  
