apiVersion: v1
kind: Service
metadata:   
  name: nginx-canary-svc
  namespace: haha
spec:       
  selector:
    app: canary
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
